### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by hfcaio** [vss2sn/tello#11]
After compiling the code, I tried to run using ./tello but I got this error:
![image](https://github.com/vss2sn/tello/assets/83253047/7376edc8-6454-44f1-bd0f-f58612c84909)

my cmake options: cmake -DRUN_SLAM=ON -DUSE_CMAKE_NOT_SCRIPT=ON -DUSE_JOYSTICK=OFF -DUSE_TERMINAL=ON

**Comment by vss2sn** [comment]
Could you clear the build folder and re-compile and try? It seems like your old CMake options are being used where `USE_JOYSTICK` was set to `ON`.

**Comment by hfcaio** [comment]
thanks for responding, but I tried deleting the build folder and now I have other problem 
![image](https://github.com/vss2sn/tello/assets/83253047/74d773b3-c72b-41e6-98a6-7be9415fd118)

**Comment by hfcaio** [comment]
thanks for responding.
I cleared the build folder and build again, and now I have other problem
![image](https://github.com/vss2sn/tello/assets/83253047/304f2db1-b530-46dc-a835-3c3b43f6f8a6)

I was in git 2.25 but I a am issue saying that this was a problem in 2.22 and newer so I tried git 2.20.0 but I am getting the same error.

**system**
- Ubuntu 20.04.6 LTS
- git 2.20
- zsh 5.8
- cmake 3.16.3
- make 4.2.1

**Comment by vss2sn** [comment]
OpenVSLAM is no longer available due to a potential copyright issue.
[Link to termination notice.](https://github.com/stella-cv/stella_vslam)
There are community forks available on GitHub that claim to replace the offending code that might suit your use case. 
If SLAM is not essential, you can run the code without SLAM, i.e., compiling the code with `-DRUN_SLAM=OFF`.
