### ISSUE TITLE
Problems when decoding the video from Tello

### ISSUE THREAD

**Issue by FreddyName** [vss2sn/tello#3]
Hi, excuse me for bothering you, i have a probelm when i decode the video stream and the info is as followed,  looking forward to your response! Thank you in advance.
info:
[h264 @ 0x22a1740] non-existing PPS 0 referenced
[h264 @ 0x22a1740] decode_slice_header error
[h264 @ 0x22a1740] no frame!
[2020-09-27 | 20:19:41 | Error--] Error in decoding frame |video_socket.cpp:168|

**Comment by vss2sn** [comment]
That occurs just as streaming starts but no compete image has been received. It should stop in a second or so, and should not affect any functionality, so it can be ignored. It seems that this is a common issue, and not repository specific as the following links show:
https://github.com/dji-sdk/Tello-Python/issues/8
https://github.com/damiafuentes/DJITelloPy/issues/21
https://stemrobotics.cs.pdx.edu/node/10495
The above links also have a contain potential solutions in case this issue is preventing the video stream from being displayed.

**Comment by vss2sn** [comment]
Closing as issue not repository specific and lack of activity.

**Comment by kinivi** [comment]
@vss2sn Have you fixed that issue?
